version: '3.8'

services:
  minio_s3:
    image: minio/minio:latest
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
    networks:
      - dota_pred
  psql_server:
    image: postgres:alpine3.17
    container_name: psql_server
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wildberries"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - minio_s3
    networks:
      - dota_pred
  mlflow_track:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: mlflow_tracking_server
    environment:
      DIALECT: ${DIALECT}
      USERNAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: psql_server
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE: ${POSTGRES_DB}
      BUCKET: ${MLFLOW_BUCKET}
      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}
      MLFLOW_S3_ENDPOINT_URL: http://172.22.0.2:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - psql_server
      - minio_s3
    networks:
      - dota_pred
  lab:
    build:
      context: .
      dockerfile: lab/Dockerfile
    container_name: jupyter_lab
    environment:
      LAB_IP: ${LAB_IP}
      LAB_PORT: ${LAB_PORT}
      MINIO_STORAGE: minio_storage
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_KEY_ID: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${LAB_PORT}:${LAB_PORT}"
    volumes:
      - ./lab/data:/app/data
    depends_on:
      - mlflow_track
    networks:
      - dota_pred

networks:
  dota_pred:
    external: true
    name: dota_pred
      
