version: '3.8'

services:
  minio_s3:
    image: minio/minio:latest
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
    networks:
      - dota_pred
  spark:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    networks:
      - dota_pred
  spark-worker_1:
    image: bitnami/spark:latest
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - dota_pred
  spark-worker_2:
    image: bitnami/spark:latest
    container_name: spark_worker_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - dota_pred
  lab:
    build:
      context: .
      dockerfile: lab/Dockerfile
    container_name: jupyter_lab
    environment:
      LAB_IP: ${LAB_IP}
      LAB_PORT: ${LAB_PORT}
      MINIO_STORAGE: minio_storage
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_KEY_ID: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${LAB_PORT}:${LAB_PORT}"
    volumes:
      - ./lab/data:/app/data
    depends_on:
      - minio_s3
    networks:
      - dota_pred

networks:
  dota_pred:
    external: true
    name: dota_pred
      
